<?php

namespace App\Presenters;

use App\Forms\ContactForm;
use App\Forms\SubscribeForm;
use App\Model\FastSpringModel;
use App\Service\Config\ApplicationConfig;
use Contributte\Translation\Translator;
use Contributte;
use DateTime;

use Nette,
    Nette\Application\UI\Form;

/**
 * @method void setLocale(string $locale)
 */


/**
 * Base presenter for all application presenters.
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    /** @persistent */
    public $locale;
    public $languages;

    // FORMS
    protected $subscribeForm;
    protected $contactForm;
    protected $contactFormSentData;

    // CONFIGS
    protected $applicationConfig;

    // SERVICES & MODELS
    //protected $translator;
    protected $detect;
    public $fastSpringModel;

    // OTHER
    protected $productCode;
    protected $pageType;
    public $customPageName; //used in contact form, as source page identification in mails/pushovers notifications for dynamicaly generated pages (such as news detail)

    //CONST
    const STATS_COOKIE = 'withdraw_statistic_cookie';

    public function __construct(SubscribeForm $subscribeForm, Translator $translator, ApplicationConfig $applicationConfig, ContactForm $contactForm)
    {
        $this->subscribeForm = $subscribeForm;
        $this->translator = $translator;
        $this->contactForm = $contactForm;
        $this->applicationConfig = $applicationConfig;
        $this->detect = new \Mobile_Detect();
    }

    public $httpRequest;

    public function injectRequest(Nette\Http\Request $httpRequest): void
    {
        $this->httpRequest = $httpRequest;
    }

    public $httpResponse;

    public function injectResponse(Nette\Http\Response $httpResponse): void
    {
        $this->httpResponse = $httpResponse;
    }

    /** @var \App\Service\Translator */
    private $translatorService;

    public function injectTranslator(\App\Service\Translator $translatorService): void
    {
        $this->translatorService = $translatorService;
    }

    public function injectFastSpringModel(FastSpringModel $fastSpringModel): void
    {
        $this->fastSpringModel = $fastSpringModel;
    }


    /** @var Contributte\Translation\Translator @inject */
    public $translator;

     /** @var Contributte\Translation\Translator @inject */
    public $translatorRouterResolver;

    public function handleChangeLocale(string $locale): void
    {
        $this->translatorRouterResolver->setLocale($locale);
        $this->redirect('this');
    }


    protected function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $this->setAffiliateCookie();

        $this->manageFirstVisitCookie();

        $this->template->appConfig = $this->applicationConfig->getConfig();
        $this->template->cookie = [
            'name' => self::STATS_COOKIE,
            'value' => $this->httpRequest->getCookie(self::STATS_COOKIE),
        ];

        $this->template->detect = array(
            "platformDevice" => $this->detect->isMobile() ? ($this->detect->isTablet() ? 'tablet' : 'phone') : 'desktop',
            "isIE" => $this->detect->version('IE') ? 'true' : 'false',
            "isEdge" => $this->detect->version('Edge') ? 'true' : 'false',
            "isChrome" => 'false',
            "isSafari" => 'false',
            "isFirefox" => $this->detect->version('Firefox') ? 'true' : 'false',
        );

        if (stripos($this->detect->getUserAgent(), 'Chrome') !== false) {
            $this->template->detect["isChrome"] = 'true';
        } elseif (stripos($this->detect->getUserAgent(), 'Safari') !== false) {
            $this->template->detect["isSafari"] = 'true';
        }

        $this->template->addFilter('genericFormatDate', function ($date) {
            $dt = new DateTime($date);
            return $dt->format('F j, Y'); 
        });


        $languages = $this->translatorService->getAvailableLanguages();
        $languages = array_values(array_diff($languages, [$this->locale]));
        $this->template->locale = $this->locale;
        $this->template->alternativeLang = $languages[0];
        $this->template->isTranslated = $this->isPageTranslated();
    }

    private function manageFirstVisitCookie()
    {
        $cookieName = $this->applicationConfig->getConfig()["first_visit_cookie_name"];
        if ($this->httpRequest->getCookie($cookieName) === null) {
            $this->httpResponse->setCookie($cookieName, date("Y-m-d H:i:s"), '1 year', '/');
        }
    }

    private function setAffiliateCookie()
    {
        $cookieConsentRaw = $this->httpRequest->getCookie("cc_cookie");

        $allowSetAffiliateCookies = true;
        if ($cookieConsentRaw !== null) {
            $cookieConsent = json_decode($cookieConsentRaw, true);
            if (!in_array("marketing", $cookieConsent["level"])) {
                $allowSetAffiliateCookies = false;
            }
        }

        if ($allowSetAffiliateCookies === true) {
            $get['affiliate'] = $this->httpRequest->getQuery('affiliate');
            $get['affiliateid'] = $this->httpRequest->getQuery('affiliateid');
            if (isset($get['affiliate'])) {
                $this->httpResponse->setCookie($this->fastSpringModel->getConfig()["affiliate_cookie"], $get['affiliate'], '24 hours', '/');
            }
            if (isset($get['affiliateid'])) {
                $this->httpResponse->setCookie($this->fastSpringModel->getConfig()["affiliate_id_cookie"], $get['affiliateid'], '24 hours', '/');
            }
        }
    }

    private function isPageTranslated()
    {
        $pageTranslations = $this->translatorService->getPageTranslations($this->presenter->getName(), $this->presenter->getAction());

        if ($pageTranslations !== false && in_array($this->locale, $pageTranslations)) {
            $isTranslated = true;
        } else {
            if ($pageTranslations === false && $this->locale === $this->translatorService->getDefaultLang()) {
                $isTranslated = true;
            } else {
                $isTranslated = false;
            }
        }
        return $isTranslated;
    }

    protected function createComponentSubscribeNewsForm()
    {
        $form = $this->subscribeForm->create();

        /** @var \Nette\Forms\Control\TextInput $formListId */
        $formListId = $form['listId'];
        $formListId->setDefaultValue($this->subscribeForm->mailChimpModel->config["lists"]["24UGENERIC_" . strtoupper($this->locale)]["id"]);

        $listTag = $this->subscribeForm->getListTag();
        if (empty($listTag)) {
            $this->subscribeForm->setListTag($this->presenter->getName());
        }


        $form->onSuccess[] = function () {
            $this->template->resultType = (in_array($this->subscribeForm->getResult(), [SubscribeForm::RESULT_USER_RESUBSCRIBE, SubscribeForm::RESULT_NEW_USER]) ? "send_email" : "no_send_email");
            $this->template->snFormSuccess = true;
        };

        $this->redrawControl('snForm');


        return $form;
    }

    protected function createComponentAdvertismenSubscribeNewsForm()
    {
        $form = $this->subscribeForm->create();

              
        /** @var \Nette\Forms\Controls\TextInput $name */
        $name = $form['name'];
        $name->setRequired($this->translator->translate(SubscribeForm::TRANSLATE_PATH . "items.name.validation.required"));

        /** @var \Nette\Forms\Controls\TextInput $surname */
        $surname = $form['surname'];
        $surname->setRequired($this->translator->translate(SubscribeForm::TRANSLATE_PATH . "items.surname.validation.required"));

        /** @var \Nette\Forms\Controls\TextInput $listId */
        $listId = $form['listId'];
        $listId->setDefaultValue($this->subscribeForm->mailChimpModel->config["lists"]["24UGENERIC_" . strtoupper($this->locale)]["id"]);

        $listTag = $this->subscribeForm->getListTag();
        if (empty($listTag)) {
            $this->subscribeForm->setListTag($this->presenter->getName());
        }


        $form->onSuccess[] = function () {
            $this->template->resultType = (in_array($this->subscribeForm->getResult(), [SubscribeForm::RESULT_USER_RESUBSCRIBE, SubscribeForm::RESULT_NEW_USER]) ? "send_email" : "no_send_email");
            $this->template->asnFormSuccess = true;
        };

        $this->redrawControl('asnForm');


        return $form;
    }


    public function timezones()
    {
        $result = array();

        // only process geographical timezones

        foreach (preg_grep('~^(?:A(?:frica|merica|ntarctica|rctic|tlantic|sia|ustralia)|Europe|Indian|Pacific)/~', timezone_identifiers_list()) as $timezone) {
            if (is_object($timezone = new \DateTimeZone($timezone)) === true) {
                $currentTimeZoneTime = new \DateTime();
                $currentTimeZoneTime->setTimezone($timezone);
                $offset = $currentTimeZoneTime->format("Z") / 3600;
                $result[str_replace(".", ",", $offset)][] = preg_replace(array('~^.*/([^/]+)$~', '~_~'), array('$1', ' '), $timezone->getName());
            }
        }


        ksort($result);

        $response = [];

        foreach ($result as $offset => $timezones) {
            $offsetNumber = (str_replace(",", ".", $offset) * 1);

            $formatedOffset = $offset;
            if (is_float($offsetNumber)) {
                list($hoursInt, $minutesDecimal) = explode(".", $offsetNumber);

                $minutes = 60 * (("0." . $minutesDecimal) * 1);
                $formatedOffset = $hoursInt . ":" . $minutes;
            } else {
                $formatedOffset = $offsetNumber . ":00";
            }


            $utcName = "(UTC " . ($offset >= 0 ? "+" . $formatedOffset : $formatedOffset) . ")";
            $response[$utcName] = $timezones;

            //$result[$zone] = preg_replace(array('~^.*/([^/]+)$~', '~_~'), array('$1', ' '), $value); // "humanize" city names
            /*
                        if (array_key_exists(1, $offset = explode('|', $key)) === true) // "humanize" the offset
                        {
                            $offset = str_replace(' +00:00', '', sprintf('(UTC %+03d:%02u)', $offset[1] / 3600, abs($offset[1]) % 3600 / 60));
                        }

                        //$result[$zone] = array_slice($result[$zone], 0, 5);
                        if (asort($result[$zone]) === true) // sort city names
                        {
                            $result2[$offset][] = trim(sprintf('%s', implode(', ', $result[$zone])));

                        }*/
        }

        $output = [];
        $timezonesOnRow = 8;
        foreach ($response as $utc => $timezones) {
            $timezones = array_chunk($timezones, $timezonesOnRow);

            foreach ($timezones as $timezoneGroupNumber => $timezoneGroup) {
                $output[$timezoneGroupNumber . "||" . $utc] = $utc . " - " . implode(", ", $timezoneGroup);
            }
        }

        return $output;
    }

    public
    function addTimezones(
        $form
    ) {
        $form->addSelect("timezones", $label = null, $this->timezones());

        return $form;
    }

    public function numberPrefix()
    {
        $prefixNumberListJson = '[{"name":"Afghanistan","dial_code":"+93","code":"AF"},{"name":"Aland Islands","dial_code":"+358","code":"AX"},{"name":"Albania","dial_code":"+355","code":"AL"},{"name":"Algeria","dial_code":"+213","code":"DZ"},{"name":"AmericanSamoa","dial_code":"+1684","code":"AS"},{"name":"Andorra","dial_code":"+376","code":"AD"},{"name":"Angola","dial_code":"+244","code":"AO"},{"name":"Anguilla","dial_code":"+1264","code":"AI"},{"name":"Antarctica","dial_code":"+672","code":"AQ"},{"name":"Antigua and Barbuda","dial_code":"+1268","code":"AG"},{"name":"Argentina","dial_code":"+54","code":"AR"},{"name":"Armenia","dial_code":"+374","code":"AM"},{"name":"Aruba","dial_code":"+297","code":"AW"},{"name":"Australia","dial_code":"+61","code":"AU"},{"name":"Austria","dial_code":"+43","code":"AT"},{"name":"Azerbaijan","dial_code":"+994","code":"AZ"},{"name":"Bahamas","dial_code":"+1242","code":"BS"},{"name":"Bahrain","dial_code":"+973","code":"BH"},{"name":"Bangladesh","dial_code":"+880","code":"BD"},{"name":"Barbados","dial_code":"+1246","code":"BB"},{"name":"Belarus","dial_code":"+375","code":"BY"},{"name":"Belgium","dial_code":"+32","code":"BE"},{"name":"Belize","dial_code":"+501","code":"BZ"},{"name":"Benin","dial_code":"+229","code":"BJ"},{"name":"Bermuda","dial_code":"+1441","code":"BM"},{"name":"Bhutan","dial_code":"+975","code":"BT"},{"name":"Bolivia, Plurinational State of","dial_code":"+591","code":"BO"},{"name":"Bosnia and Herzegovina","dial_code":"+387","code":"BA"},{"name":"Botswana","dial_code":"+267","code":"BW"},{"name":"Brazil","dial_code":"+55","code":"BR"},{"name":"British Indian Ocean Territory","dial_code":"+246","code":"IO"},{"name":"Brunei Darussalam","dial_code":"+673","code":"BN"},{"name":"Bulgaria","dial_code":"+359","code":"BG"},{"name":"Burkina Faso","dial_code":"+226","code":"BF"},{"name":"Burundi","dial_code":"+257","code":"BI"},{"name":"Cambodia","dial_code":"+855","code":"KH"},{"name":"Cameroon","dial_code":"+237","code":"CM"},{"name":"Canada","dial_code":"+1","code":"CA"},{"name":"Cape Verde","dial_code":"+238","code":"CV"},{"name":"Cayman Islands","dial_code":"+1 345","code":"KY"},{"name":"Central African Republic","dial_code":"+236","code":"CF"},{"name":"Chad","dial_code":"+235","code":"TD"},{"name":"Chile","dial_code":"+56","code":"CL"},{"name":"China","dial_code":"+86","code":"CN"},{"name":"Christmas Island","dial_code":"+61","code":"CX"},{"name":"Cocos (Keeling) Islands","dial_code":"+61","code":"CC"},{"name":"Colombia","dial_code":"+57","code":"CO"},{"name":"Comoros","dial_code":"+269","code":"KM"},{"name":"Congo","dial_code":"+242","code":"CG"},{"name":"Congo, The Democratic Republic of the Congo","dial_code":"+243","code":"CD"},{"name":"Cook Islands","dial_code":"+682","code":"CK"},{"name":"Costa Rica","dial_code":"+506","code":"CR"},{"name":"Cote d\'Ivoire","dial_code":"+225","code":"CI"},{"name":"Croatia","dial_code":"+385","code":"HR"},{"name":"Cuba","dial_code":"+53","code":"CU"},{"name":"Cyprus","dial_code":"+357","code":"CY"},{"name":"Czech Republic","dial_code":"+420","code":"CZ"},{"name":"Denmark","dial_code":"+45","code":"DK"},{"name":"Djibouti","dial_code":"+253","code":"DJ"},{"name":"Dominica","dial_code":"+1767","code":"DM"},{"name":"Dominican Republic","dial_code":"+1849","code":"DO"},{"name":"Ecuador","dial_code":"+593","code":"EC"},{"name":"Egypt","dial_code":"+20","code":"EG"},{"name":"El Salvador","dial_code":"+503","code":"SV"},{"name":"Equatorial Guinea","dial_code":"+240","code":"GQ"},{"name":"Eritrea","dial_code":"+291","code":"ER"},{"name":"Estonia","dial_code":"+372","code":"EE"},{"name":"Ethiopia","dial_code":"+251","code":"ET"},{"name":"Falkland Islands (Malvinas)","dial_code":"+500","code":"FK"},{"name":"Faroe Islands","dial_code":"+298","code":"FO"},{"name":"Fiji","dial_code":"+679","code":"FJ"},{"name":"Finland","dial_code":"+358","code":"FI"},{"name":"France","dial_code":"+33","code":"FR"},{"name":"French Guiana","dial_code":"+594","code":"GF"},{"name":"French Polynesia","dial_code":"+689","code":"PF"},{"name":"Gabon","dial_code":"+241","code":"GA"},{"name":"Gambia","dial_code":"+220","code":"GM"},{"name":"Georgia","dial_code":"+995","code":"GE"},{"name":"Germany","dial_code":"+49","code":"DE"},{"name":"Ghana","dial_code":"+233","code":"GH"},{"name":"Gibraltar","dial_code":"+350","code":"GI"},{"name":"Greece","dial_code":"+30","code":"GR"},{"name":"Greenland","dial_code":"+299","code":"GL"},{"name":"Grenada","dial_code":"+1473","code":"GD"},{"name":"Guadeloupe","dial_code":"+590","code":"GP"},{"name":"Guam","dial_code":"+1671","code":"GU"},{"name":"Guatemala","dial_code":"+502","code":"GT"},{"name":"Guernsey","dial_code":"+44","code":"GG"},{"name":"Guinea","dial_code":"+224","code":"GN"},{"name":"Guinea-Bissau","dial_code":"+245","code":"GW"},{"name":"Guyana","dial_code":"+595","code":"GY"},{"name":"Haiti","dial_code":"+509","code":"HT"},{"name":"Holy See (Vatican City State)","dial_code":"+379","code":"VA"},{"name":"Honduras","dial_code":"+504","code":"HN"},{"name":"Hong Kong","dial_code":"+852","code":"HK"},{"name":"Hungary","dial_code":"+36","code":"HU"},{"name":"Iceland","dial_code":"+354","code":"IS"},{"name":"India","dial_code":"+91","code":"IN"},{"name":"Indonesia","dial_code":"+62","code":"ID"},{"name":"Iran, Islamic Republic of Persian Gulf","dial_code":"+98","code":"IR"},{"name":"Iraq","dial_code":"+964","code":"IQ"},{"name":"Ireland","dial_code":"+353","code":"IE"},{"name":"Isle of Man","dial_code":"+44","code":"IM"},{"name":"Israel","dial_code":"+972","code":"IL"},{"name":"Italy","dial_code":"+39","code":"IT"},{"name":"Jamaica","dial_code":"+1876","code":"JM"},{"name":"Japan","dial_code":"+81","code":"JP"},{"name":"Jersey","dial_code":"+44","code":"JE"},{"name":"Jordan","dial_code":"+962","code":"JO"},{"name":"Kazakhstan","dial_code":"+77","code":"KZ"},{"name":"Kenya","dial_code":"+254","code":"KE"},{"name":"Kiribati","dial_code":"+686","code":"KI"},{"name":"Korea, Democratic People\'s Republic of Korea","dial_code":"+850","code":"KP"},{"name":"Korea, Republic of South Korea","dial_code":"+82","code":"KR"},{"name":"Kuwait","dial_code":"+965","code":"KW"},{"name":"Kyrgyzstan","dial_code":"+996","code":"KG"},{"name":"Laos","dial_code":"+856","code":"LA"},{"name":"Latvia","dial_code":"+371","code":"LV"},{"name":"Lebanon","dial_code":"+961","code":"LB"},{"name":"Lesotho","dial_code":"+266","code":"LS"},{"name":"Liberia","dial_code":"+231","code":"LR"},{"name":"Libyan Arab Jamahiriya","dial_code":"+218","code":"LY"},{"name":"Liechtenstein","dial_code":"+423","code":"LI"},{"name":"Lithuania","dial_code":"+370","code":"LT"},{"name":"Luxembourg","dial_code":"+352","code":"LU"},{"name":"Macao","dial_code":"+853","code":"MO"},{"name":"Macedonia","dial_code":"+389","code":"MK"},{"name":"Madagascar","dial_code":"+261","code":"MG"},{"name":"Malawi","dial_code":"+265","code":"MW"},{"name":"Malaysia","dial_code":"+60","code":"MY"},{"name":"Maldives","dial_code":"+960","code":"MV"},{"name":"Mali","dial_code":"+223","code":"ML"},{"name":"Malta","dial_code":"+356","code":"MT"},{"name":"Marshall Islands","dial_code":"+692","code":"MH"},{"name":"Martinique","dial_code":"+596","code":"MQ"},{"name":"Mauritania","dial_code":"+222","code":"MR"},{"name":"Mauritius","dial_code":"+230","code":"MU"},{"name":"Mayotte","dial_code":"+262","code":"YT"},{"name":"Mexico","dial_code":"+52","code":"MX"},{"name":"Micronesia, Federated States of Micronesia","dial_code":"+691","code":"FM"},{"name":"Moldova","dial_code":"+373","code":"MD"},{"name":"Monaco","dial_code":"+377","code":"MC"},{"name":"Mongolia","dial_code":"+976","code":"MN"},{"name":"Montenegro","dial_code":"+382","code":"ME"},{"name":"Montserrat","dial_code":"+1664","code":"MS"},{"name":"Morocco","dial_code":"+212","code":"MA"},{"name":"Mozambique","dial_code":"+258","code":"MZ"},{"name":"Myanmar","dial_code":"+95","code":"MM"},{"name":"Namibia","dial_code":"+264","code":"NA"},{"name":"Nauru","dial_code":"+674","code":"NR"},{"name":"Nepal","dial_code":"+977","code":"NP"},{"name":"Netherlands","dial_code":"+31","code":"NL"},{"name":"Netherlands Antilles","dial_code":"+599","code":"AN"},{"name":"New Caledonia","dial_code":"+687","code":"NC"},{"name":"New Zealand","dial_code":"+64","code":"NZ"},{"name":"Nicaragua","dial_code":"+505","code":"NI"},{"name":"Niger","dial_code":"+227","code":"NE"},{"name":"Nigeria","dial_code":"+234","code":"NG"},{"name":"Niue","dial_code":"+683","code":"NU"},{"name":"Norfolk Island","dial_code":"+672","code":"NF"},{"name":"Northern Mariana Islands","dial_code":"+1670","code":"MP"},{"name":"Norway","dial_code":"+47","code":"NO"},{"name":"Oman","dial_code":"+968","code":"OM"},{"name":"Pakistan","dial_code":"+92","code":"PK"},{"name":"Palau","dial_code":"+680","code":"PW"},{"name":"Palestinian Territory, Occupied","dial_code":"+970","code":"PS"},{"name":"Panama","dial_code":"+507","code":"PA"},{"name":"Papua New Guinea","dial_code":"+675","code":"PG"},{"name":"Paraguay","dial_code":"+595","code":"PY"},{"name":"Peru","dial_code":"+51","code":"PE"},{"name":"Philippines","dial_code":"+63","code":"PH"},{"name":"Pitcairn","dial_code":"+872","code":"PN"},{"name":"Poland","dial_code":"+48","code":"PL"},{"name":"Portugal","dial_code":"+351","code":"PT"},{"name":"Puerto Rico","dial_code":"+1939","code":"PR"},{"name":"Qatar","dial_code":"+974","code":"QA"},{"name":"Romania","dial_code":"+40","code":"RO"},{"name":"Russia","dial_code":"+7","code":"RU"},{"name":"Rwanda","dial_code":"+250","code":"RW"},{"name":"Reunion","dial_code":"+262","code":"RE"},{"name":"Saint Barthelemy","dial_code":"+590","code":"BL"},{"name":"Saint Helena, Ascension and Tristan Da Cunha","dial_code":"+290","code":"SH"},{"name":"Saint Kitts and Nevis","dial_code":"+1869","code":"KN"},{"name":"Saint Lucia","dial_code":"+1758","code":"LC"},{"name":"Saint Martin","dial_code":"+590","code":"MF"},{"name":"Saint Pierre and Miquelon","dial_code":"+508","code":"PM"},{"name":"Saint Vincent and the Grenadines","dial_code":"+1784","code":"VC"},{"name":"Samoa","dial_code":"+685","code":"WS"},{"name":"San Marino","dial_code":"+378","code":"SM"},{"name":"Sao Tome and Principe","dial_code":"+239","code":"ST"},{"name":"Saudi Arabia","dial_code":"+966","code":"SA"},{"name":"Senegal","dial_code":"+221","code":"SN"},{"name":"Serbia","dial_code":"+381","code":"RS"},{"name":"Seychelles","dial_code":"+248","code":"SC"},{"name":"Sierra Leone","dial_code":"+232","code":"SL"},{"name":"Singapore","dial_code":"+65","code":"SG"},{"name":"Slovakia","dial_code":"+421","code":"SK"},{"name":"Slovenia","dial_code":"+386","code":"SI"},{"name":"Solomon Islands","dial_code":"+677","code":"SB"},{"name":"Somalia","dial_code":"+252","code":"SO"},{"name":"South Africa","dial_code":"+27","code":"ZA"},{"name":"South Sudan","dial_code":"+211","code":"SS"},{"name":"South Georgia and the South Sandwich Islands","dial_code":"+500","code":"GS"},{"name":"Spain","dial_code":"+34","code":"ES"},{"name":"Sri Lanka","dial_code":"+94","code":"LK"},{"name":"Sudan","dial_code":"+249","code":"SD"},{"name":"Suriname","dial_code":"+597","code":"SR"},{"name":"Svalbard and Jan Mayen","dial_code":"+47","code":"SJ"},{"name":"Swaziland","dial_code":"+268","code":"SZ"},{"name":"Sweden","dial_code":"+46","code":"SE"},{"name":"Switzerland","dial_code":"+41","code":"CH"},{"name":"Syrian Arab Republic","dial_code":"+963","code":"SY"},{"name":"Taiwan","dial_code":"+886","code":"TW"},{"name":"Tajikistan","dial_code":"+992","code":"TJ"},{"name":"Tanzania, United Republic of Tanzania","dial_code":"+255","code":"TZ"},{"name":"Thailand","dial_code":"+66","code":"TH"},{"name":"Timor-Leste","dial_code":"+670","code":"TL"},{"name":"Togo","dial_code":"+228","code":"TG"},{"name":"Tokelau","dial_code":"+690","code":"TK"},{"name":"Tonga","dial_code":"+676","code":"TO"},{"name":"Trinidad and Tobago","dial_code":"+1868","code":"TT"},{"name":"Tunisia","dial_code":"+216","code":"TN"},{"name":"Turkey","dial_code":"+90","code":"TR"},{"name":"Turkmenistan","dial_code":"+993","code":"TM"},{"name":"Turks and Caicos Islands","dial_code":"+1649","code":"TC"},{"name":"Tuvalu","dial_code":"+688","code":"TV"},{"name":"Uganda","dial_code":"+256","code":"UG"},{"name":"Ukraine","dial_code":"+380","code":"UA"},{"name":"United Arab Emirates","dial_code":"+971","code":"AE"},{"name":"United Kingdom","dial_code":"+44","code":"GB"},{"name":"United States","dial_code":"+1","code":"US"},{"name":"Uruguay","dial_code":"+598","code":"UY"},{"name":"Uzbekistan","dial_code":"+998","code":"UZ"},{"name":"Vanuatu","dial_code":"+678","code":"VU"},{"name":"Venezuela, Bolivarian Republic of Venezuela","dial_code":"+58","code":"VE"},{"name":"Vietnam","dial_code":"+84","code":"VN"},{"name":"Virgin Islands, British","dial_code":"+1284","code":"VG"},{"name":"Virgin Islands, U.S.","dial_code":"+1340","code":"VI"},{"name":"Wallis and Futuna","dial_code":"+681","code":"WF"},{"name":"Yemen","dial_code":"+967","code":"YE"},{"name":"Zambia","dial_code":"+260","code":"ZM"},{"name":"Zimbabwe","dial_code":"+263","code":"ZW"}]';
        $prefixNumberList = json_decode($prefixNumberListJson, true);
        $prefix = [];

        foreach ($prefixNumberList as $country => $countryDetail) {
            $prefix[$countryDetail["code"]] = $countryDetail["dial_code"] . ' (' . $countryDetail["name"] . ')';
        }
        return $prefix;
    }

    public
    function addNumberPrefix(
        $form
    ) {
        //$prefixNumberListJson = '{"countries":[{"code":"+7 840","name":"Abkhazia"},{"code":"+93","name":"Afghanistan"},{"code":"+355","name":"Albania"},{"code":"+213","name":"Algeria"},{"code":"+1 684","name":"American Samoa"},{"code":"+376","name":"Andorra"},{"code":"+244","name":"Angola"},{"code":"+1 264","name":"Anguilla"},{"code":"+1 268","name":"Antigua and Barbuda"},{"code":"+54","name":"Argentina"},{"code":"+374","name":"Armenia"},{"code":"+297","name":"Aruba"},{"code":"+247","name":"Ascension"},{"code":"+61","name":"Australia"},{"code":"+672","name":"Australian External Territories"},{"code":"+43","name":"Austria"},{"code":"+994","name":"Azerbaijan"},{"code":"+1 242","name":"Bahamas"},{"code":"+973","name":"Bahrain"},{"code":"+880","name":"Bangladesh"},{"code":"+1 246","name":"Barbados"},{"code":"+1 268","name":"Barbuda"},{"code":"+375","name":"Belarus"},{"code":"+32","name":"Belgium"},{"code":"+501","name":"Belize"},{"code":"+229","name":"Benin"},{"code":"+1 441","name":"Bermuda"},{"code":"+975","name":"Bhutan"},{"code":"+591","name":"Bolivia"},{"code":"+387","name":"Bosnia and Herzegovina"},{"code":"+267","name":"Botswana"},{"code":"+55","name":"Brazil"},{"code":"+246","name":"British Indian Ocean Territory"},{"code":"+1 284","name":"British Virgin Islands"},{"code":"+673","name":"Brunei"},{"code":"+359","name":"Bulgaria"},{"code":"+226","name":"Burkina Faso"},{"code":"+257","name":"Burundi"},{"code":"+855","name":"Cambodia"},{"code":"+237","name":"Cameroon"},{"code":"+1","name":"Canada"},{"code":"+238","name":"Cape Verde"},{"code":"+ 345","name":"Cayman Islands"},{"code":"+236","name":"Central African Republic"},{"code":"+235","name":"Chad"},{"code":"+56","name":"Chile"},{"code":"+86","name":"China"},{"code":"+61","name":"Christmas Island"},{"code":"+61","name":"Cocos-Keeling Islands"},{"code":"+57","name":"Colombia"},{"code":"+269","name":"Comoros"},{"code":"+242","name":"Congo"},{"code":"+243","name":"Congo, Dem. Rep. of (Zaire)"},{"code":"+682","name":"Cook Islands"},{"code":"+506","name":"Costa Rica"},{"code":"+385","name":"Croatia"},{"code":"+53","name":"Cuba"},{"code":"+599","name":"Curacao"},{"code":"+537","name":"Cyprus"},{"code":"+420","name":"Czech Republic"},{"code":"+45","name":"Denmark"},{"code":"+246","name":"Diego Garcia"},{"code":"+253","name":"Djibouti"},{"code":"+1 767","name":"Dominica"},{"code":"+1 809","name":"Dominican Republic"},{"code":"+670","name":"East Timor"},{"code":"+56","name":"Easter Island"},{"code":"+593","name":"Ecuador"},{"code":"+20","name":"Egypt"},{"code":"+503","name":"El Salvador"},{"code":"+240","name":"Equatorial Guinea"},{"code":"+291","name":"Eritrea"},{"code":"+372","name":"Estonia"},{"code":"+251","name":"Ethiopia"},{"code":"+500","name":"Falkland Islands"},{"code":"+298","name":"Faroe Islands"},{"code":"+679","name":"Fiji"},{"code":"+358","name":"Finland"},{"code":"+33","name":"France"},{"code":"+596","name":"French Antilles"},{"code":"+594","name":"French Guiana"},{"code":"+689","name":"French Polynesia"},{"code":"+241","name":"Gabon"},{"code":"+220","name":"Gambia"},{"code":"+995","name":"Georgia"},{"code":"+49","name":"Germany"},{"code":"+233","name":"Ghana"},{"code":"+350","name":"Gibraltar"},{"code":"+30","name":"Greece"},{"code":"+299","name":"Greenland"},{"code":"+1 473","name":"Grenada"},{"code":"+590","name":"Guadeloupe"},{"code":"+1 671","name":"Guam"},{"code":"+502","name":"Guatemala"},{"code":"+224","name":"Guinea"},{"code":"+245","name":"Guinea-Bissau"},{"code":"+595","name":"Guyana"},{"code":"+509","name":"Haiti"},{"code":"+504","name":"Honduras"},{"code":"+852","name":"Hong Kong SAR China"},{"code":"+36","name":"Hungary"},{"code":"+354","name":"Iceland"},{"code":"+91","name":"India"},{"code":"+62","name":"Indonesia"},{"code":"+98","name":"Iran"},{"code":"+964","name":"Iraq"},{"code":"+353","name":"Ireland"},{"code":"+972","name":"Israel"},{"code":"+39","name":"Italy"},{"code":"+225","name":"Ivory Coast"},{"code":"+1 876","name":"Jamaica"},{"code":"+81","name":"Japan"},{"code":"+962","name":"Jordan"},{"code":"+7 7","name":"Kazakhstan"},{"code":"+254","name":"Kenya"},{"code":"+686","name":"Kiribati"},{"code":"+965","name":"Kuwait"},{"code":"+996","name":"Kyrgyzstan"},{"code":"+856","name":"Laos"},{"code":"+371","name":"Latvia"},{"code":"+961","name":"Lebanon"},{"code":"+266","name":"Lesotho"},{"code":"+231","name":"Liberia"},{"code":"+218","name":"Libya"},{"code":"+423","name":"Liechtenstein"},{"code":"+370","name":"Lithuania"},{"code":"+352","name":"Luxembourg"},{"code":"+853","name":"Macau SAR China"},{"code":"+389","name":"Macedonia"},{"code":"+261","name":"Madagascar"},{"code":"+265","name":"Malawi"},{"code":"+60","name":"Malaysia"},{"code":"+960","name":"Maldives"},{"code":"+223","name":"Mali"},{"code":"+356","name":"Malta"},{"code":"+692","name":"Marshall Islands"},{"code":"+596","name":"Martinique"},{"code":"+222","name":"Mauritania"},{"code":"+230","name":"Mauritius"},{"code":"+262","name":"Mayotte"},{"code":"+52","name":"Mexico"},{"code":"+691","name":"Micronesia"},{"code":"+1 808","name":"Midway Island"},{"code":"+373","name":"Moldova"},{"code":"+377","name":"Monaco"},{"code":"+976","name":"Mongolia"},{"code":"+382","name":"Montenegro"},{"code":"+1664","name":"Montserrat"},{"code":"+212","name":"Morocco"},{"code":"+95","name":"Myanmar"},{"code":"+264","name":"Namibia"},{"code":"+674","name":"Nauru"},{"code":"+977","name":"Nepal"},{"code":"+31","name":"Netherlands"},{"code":"+599","name":"Netherlands Antilles"},{"code":"+1 869","name":"Nevis"},{"code":"+687","name":"New Caledonia"},{"code":"+64","name":"New Zealand"},{"code":"+505","name":"Nicaragua"},{"code":"+227","name":"Niger"},{"code":"+234","name":"Nigeria"},{"code":"+683","name":"Niue"},{"code":"+672","name":"Norfolk Island"},{"code":"+850","name":"North Korea"},{"code":"+1 670","name":"Northern Mariana Islands"},{"code":"+47","name":"Norway"},{"code":"+968","name":"Oman"},{"code":"+92","name":"Pakistan"},{"code":"+680","name":"Palau"},{"code":"+970","name":"Palestinian Territory"},{"code":"+507","name":"Panama"},{"code":"+675","name":"Papua New Guinea"},{"code":"+595","name":"Paraguay"},{"code":"+51","name":"Peru"},{"code":"+63","name":"Philippines"},{"code":"+48","name":"Poland"},{"code":"+351","name":"Portugal"},{"code":"+1 787","name":"Puerto Rico"},{"code":"+974","name":"Qatar"},{"code":"+262","name":"Reunion"},{"code":"+40","name":"Romania"},{"code":"+7","name":"Russia"},{"code":"+250","name":"Rwanda"},{"code":"+685","name":"Samoa"},{"code":"+378","name":"San Marino"},{"code":"+966","name":"Saudi Arabia"},{"code":"+221","name":"Senegal"},{"code":"+381","name":"Serbia"},{"code":"+248","name":"Seychelles"},{"code":"+232","name":"Sierra Leone"},{"code":"+65","name":"Singapore"},{"code":"+421","name":"Slovakia"},{"code":"+386","name":"Slovenia"},{"code":"+677","name":"Solomon Islands"},{"code":"+27","name":"South Africa"},{"code":"+500","name":"South Georgia and the South Sandwich Islands"},{"code":"+82","name":"South Korea"},{"code":"+34","name":"Spain"},{"code":"+94","name":"Sri Lanka"},{"code":"+249","name":"Sudan"},{"code":"+597","name":"Suriname"},{"code":"+268","name":"Swaziland"},{"code":"+46","name":"Sweden"},{"code":"+41","name":"Switzerland"},{"code":"+963","name":"Syria"},{"code":"+886","name":"Taiwan"},{"code":"+992","name":"Tajikistan"},{"code":"+255","name":"Tanzania"},{"code":"+66","name":"Thailand"},{"code":"+670","name":"Timor Leste"},{"code":"+228","name":"Togo"},{"code":"+690","name":"Tokelau"},{"code":"+676","name":"Tonga"},{"code":"+1 868","name":"Trinidad and Tobago"},{"code":"+216","name":"Tunisia"},{"code":"+90","name":"Turkey"},{"code":"+993","name":"Turkmenistan"},{"code":"+1 649","name":"Turks and Caicos Islands"},{"code":"+688","name":"Tuvalu"},{"code":"+1 340","name":"U.S. Virgin Islands"},{"code":"+256","name":"Uganda"},{"code":"+380","name":"Ukraine"},{"code":"+971","name":"United Arab Emirates"},{"code":"+44","name":"United Kingdom"},{"code":"+1","name":"United States"},{"code":"+598","name":"Uruguay"},{"code":"+998","name":"Uzbekistan"},{"code":"+678","name":"Vanuatu"},{"code":"+58","name":"Venezuela"},{"code":"+84","name":"Vietnam"},{"code":"+1 808","name":"Wake Island"},{"code":"+681","name":"Wallis and Futuna"},{"code":"+967","name":"Yemen"},{"code":"+260","name":"Zambia"},{"code":"+255","name":"Zanzibar"},{"code":"+263","name":"Zimbabwe"}]}';
        $prefix = $this->numberPrefix();

        $form->addSelect("prefix_number", $label = null, $prefix);

        return $form;
    }

    protected
    function setAdvertisment(
        $config
    ) {
    }

    protected function createComponentCreateFooterContactForm()
    {
        $form = $this->contactForm->create();

        if (isset($this->customPageName)) {
            $this->contactForm->setCurrentPage($this->presenter->getName() . ' [' . $this->customPageName . ']');
        } else {
            $this->contactForm->setCurrentPage($this->presenter->getName());
        }

         /** @var \Nette\Forms\Controls\TextInput $formType */
        $formType = $form["type"];

        /** @var \Nette\Forms\Controls\TextInput $formName */
        $formName = $form["name"];

        /** @var \Nette\Forms\Controls\TextInput $formEmail */
        $formEmail = $form["email"];

        /** @var \Nette\Forms\Controls\TextArea $formMessage */
        $formMessage = $form["message"];

        $formType->setDefaultValue("footer");

        $formName->setRequired($this->translator->translate(ContactForm::TRANSLATE_PATH . "items.name.validation.required"));
        $formEmail->setRequired($this->translator->translate(ContactForm::TRANSLATE_PATH . "items.email.validation.required"));
        $formMessage->setRequired($this->translator->translate(ContactForm::TRANSLATE_PATH . "items.message.validation.required"));

        $c1 = date('j') + 3;
        $c2 = date('N') + 2;
        $s = $c1 + $c2;

        $form->addText('spamSecureSum', sprintf('Sum the numbers %s+%s', $c1, $c2))
            ->setHtmlAttribute("placeholder", sprintf('Sum the numbers %s+%s', $c1, $c2))
            ->setHtmlAttribute("id", "frm-ft-spamSecureSum")
            ->setHtmlAttribute("class", "frm-ft-spamSecureSum")
            ->setRequired('Unknown error, please refresh the page')
            ->addRule(Form::Equal, 'Unknown error, please refresh the page', $s);
        $form->addHidden('c1', $c1)
            ->setHtmlAttribute("id", "frm-ft-c1");
        $form->addHidden('c2', $c2)
            ->setHtmlAttribute("id", "frm-ft-c2");
        $form->addHidden('formIdent');

        unset($form['number']);
        unset($form['topic']);
        unset($form['predata']);

        $form->onSuccess[] = function ($form) {
            if ($form->getValues()['formIdent'] == 'popup') {
                $this->template->footerContactFormPopupSuccess = true;
            } else {
                $this->template->footerContactFormSuccess = true;
            }
            //$this->template->footerContactFormSuccess = true;
            $this->setContactFormSentData($form->getValues());
        };

        $this->redrawControl('footerContactForm');
        $this->redrawControl('footerContactPopupForm');

        return $form;
    }

    /**
     * @param mixed $contactFormSentData
     */
    public function setContactFormSentData($contactFormSentData)
    {
        $this->contactFormSentData = $contactFormSentData;
    }

    /**
     * @return mixed
     */
    public function getContactFormSentData()
    {
        return $this->contactFormSentData;
    }
}
